version: "3.9"

services:
  # 🟢 MongoDB
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  # 🟣 Backend (Node + Express + Mongoose + Puppeteer)
  backend:
    build: ./backend
    container_name: handtalk-backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/handtalk_accessibility
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    command: npm run dev

  # 🟡 Frontend (Vite)
  frontend:
    build: ./frontend
    container_name: handtalk-frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo-data:
